### ISSUE TITLE
TestVl3_dns is unstable

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/integration-k8s-kind#750]
## Run
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/3532109802/jobs/5926061937
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/3540144463/jobs/5942852833

## Logs
[v1.23.12.zip](https://github.com/networkservicemesh/integration-k8s-kind/files/10083338/v1.23.12.zip)

## Subtasks
- [x] Test vl3_dns many times on CI and locally ~ 6h
- [x] Reduce ping params in all `for` loops ~ 2h
- [ ] Fix empty dns address error in `cmd-nse-vl3-vpp` ~ 4h

**Comment by NikitaSkrynnik** [comment]
## PRs
https://github.com/networkservicemesh/sdk/pull/1392

**Comment by glazychev-art** [comment]
Fixed

**Comment by glazychev-art** [comment]
Still unstable
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4200384754/jobs/7286343654

**Comment by glazychev-art** [comment]
https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4230258596/jobs/7347394373
[v1.25.2.zip](https://github.com/networkservicemesh/integration-k8s-kind/files/10800353/v1.25.2.zip)

**Comment by denis-tingaikin** [comment]
Seems like done.
