### ISSUE TITLE
Add performance testing scripts and job for release workflow

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-k8s-kind#796]
## Motivation

It'd be very useful to monitor our perfomance metrics on releasing candidates. It could help to catch performance issues.

## TODO

- [ ] check scrits (AWS2AWS)
- [ ] prepare scripts for githunb workflow
- [ ] add perormance testing step on releasing (kind2kind)

**Comment by d-uzlov** [comment]
The action plan:

* [x] Run MSM perf test scripts manually with AWS2AWS scenario
* [ ] Add vl3 test
    * Adopt deployment configs from MSM testing ~4h
    * Run the test manually to ensure that it works ~4h
* [ ] Add interdomain kernel2wireguard2kernel test
    * Adopt deployment configs from MSM testing ~4h
    * Run the test manually to ensure that it works ~4h
* [ ] Add test scripts and deployments to this repo ~2h
* [ ] Add CI configs to run test scripts ~2h
* [ ] Trigger CI testing to ensure that everything works ~1h

**Comment by denis-tingaikin** [comment]
Seems like done
